# 스프링 부트 애플리케이션 설정 파일
spring:
  # 데이터베이스 설정
  datasource:
    # H2 데이터베이스 URL - 인메모리 데이터베이스 사용
    url: jdbc:h2:mem:testdb
    # H2 데이터베이스 드라이버 클래스
    driver-class-name: org.h2.Driver
    # 데이터베이스 사용자명
    username: sa
    # 데이터베이스 비밀번호
    password:

  # H2 콘솔 설정 - 웹 브라우저에서 데이터베이스 확인 가능
  h2:
    # H2 콘솔 활성화
    console:
      enabled: true
      # 콘솔 경로 설정
      path: /h2-console

  # JPA 설정
  jpa:
    # Hibernate 설정
    hibernate:
      # DDL 자동 생성 설정 - 개발 시 테이블 자동 생성
      ddl-auto: create-drop
    # SQL 로그 출력 설정
    show-sql: true
    # SQL 로그 포맷팅 설정
    properties:
      hibernate:
        # SQL 로그 포맷팅 활성화
        format_sql: true
        # SQL 로그에 파라미터 값 출력
        use_sql_comments: true
    # 데이터베이스 방언 설정 (H2는 자동 감지되므로 제거 가능)
    # database-platform: org.hibernate.dialect.H2Dialect

# 서버 포트 설정
server:
  port: 8080

# 로깅 설정
logging:
  # JPA 관련 로그 레벨 설정
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
